name: Build and Deploy to VPS

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:    
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - name: Copy Source Code over SSH
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                password: ${{ secrets.VPS_PASS }}
                source: "./"
                target: "~/api"
        
            - name: Build on Server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                password: ${{ secrets.VPS_PASS }}
                script: |
                  export NVM_DIR=~/.nvm
                  source ~/.nvm/nvm.sh
                  cd ~/api
                  npm install typescript
                  npm install
                  npm run build
                  node dist/index.js