name: Build and Deploy to VPS

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
    
        - name: Install Dependencies
          run: npm i
    
        - name: Install Dependencies
          run: npm i typescript

        - name: Build
          run: npm run build
    
        - name: Archive Production Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: dist
            path: dist/
    
    deploy:
        needs: build
        runs-on: ubuntu-latest
    
        steps:
        - name: Download Build Artifacts
          uses: actions/download-artifact@v2
          with:
            name: dist
    
        - name: Copy Artifacts over SSH
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            password: ${{ secrets.VPS_PASS }}
            source: "./"
            target: "~/api"
    
        - name: Restart server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            password: ${{ secrets.VPS_PASS }}
            script: |
                cd ~/api
                ~/.nvm/versions/node/v16.18.0/bin/npm install
                ~/.nvm/versions/node/v16.18.0/bin/node index.js