name: Build and Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Typescript and Dependencies
      run: npm run pre-build

    - name: Build
      run: npm run build

    - name: Archive Production Artifacts  
      uses: actions/upload-artifact@v2  
      with:  
        name: source  
        path: ./  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}

    steps:  
    - name: Download Build Artifacts  
      uses: actions/download-artifact@v2  
      with:  
        name: source 

    - name: Copy Source Code over SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        source: "./"
        target: "~/api"

    - name: Run or Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ~/api
          nohup node dist/index.js > output.log 2>&1 &
